using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x02000695 RID: 1685
	internal enum IIDENTITYAUTHORITY_DEFINITION_IDENTITY_TO_TEXT_FLAGS
	{
		// Token: 0x0400220A RID: 8714
		IIDENTITYAUTHORITY_DEFINITION_IDENTITY_TO_TEXT_FLAG_CANONICAL = 1
	}
}
