using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x02000697 RID: 1687
	internal enum IIDENTITYAUTHORITY_DOES_DEFINITION_MATCH_REFERENCE_FLAGS
	{
		// Token: 0x0400220E RID: 8718
		IIDENTITYAUTHORITY_DOES_DEFINITION_MATCH_REFERENCE_FLAG_EXACT_MATCH_REQUIRED = 1
	}
}
